language: python
cache: pip
sudo: false

env:
  global:
    - PILLOW="Pillow"

matrix:
  include:
    - python: 3.5
      env: PILLOW="Pillow==4.0.0"
    - python: 3.6


addons:
  apt:
    sources:
      - trusty-media
    packages:
      - ubuntu-restricted-extras
      - ffmpeg
      - libavcodec-extra-54
      # Dependencies to build PIL
      - libfreetype6-dev
      - libjpeg8-dev
      - zlib1g-dev

install:
    - pip install -U pip setuptools wheel
    - pip install -q $PILLOW
    - pip install pytest pytest-cov codecov feedgenerator zopfli brotli
    - pip install .

before_script:
  ffmpeg --help

script: py.test -sv --cov sigal --cov-report term-missing tests/

after_success:
    codecov

notifications:
    irc: "chat.freenode.net#sigal"
