language: python
python:
    - "2.7"
    - "2.6"
before_install:
    # Dependencies to build PIL
    - sudo apt-get update -qq
    - sudo apt-get install -qq libfreetype6-dev libjpeg8-dev zlib1g-dev
install:
    - pip install pytest --use-mirrors
    - pip install . --use-mirrors
script: pytest
